version: "3.8"

services:
  flask:
    build: ./flask-app
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - APP_IP=0.0.0.0
      - APP_PORT=5000
      - MONGO_URL=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
